[package]
name = "storage"
version = "0.1.0"
authors = ["Alec Von Arx <al.vonarx@gmail.com>"]
edition = "2018"

[dependencies]
# 1p
game-api = { path = "../game-api" }

# 3p

[dev-dependencies]
rand = "=0.7.3"