[package]
name = "lost-cities-game"
version = "0.1.0"
authors = ["Alec Von Arx <alecva@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
