[workspace]
members = [
  "src/crates/backend-engine",
  "src/crates/bin-client",
  "src/crates/bin-server",
  "src/crates/client-engine",
  "src/crates/game-api",
  "src/crates/rules",
  "src/crates/storage",
]
