[package]
name = "rules"
version = "0.1.0"
authors = ["Alec Von Arx <al.vonarx@gmail.com>"]
edition = "2018"

[dependencies]
# 1p
game-api = { path = "../game-api" }

# 3p
rand = "=0.7.3"
rand_core = "=0.5.1"
