[package]
name = "api"
version = "0.1.0"
authors = ["Alec Von Arx <al.vonarx@gmail.com>"]
edition = "2018"

[dependencies]
# Local repo dependencies
storage = { path = "../storage" }
types = { path = "../types" }
rules = { path = "../rules" }

# External dependencies
rand = "=0.7.3"
