[package]
name = "game-api"
version = "0.1.0"
authors = ["Alec Von Arx <al.vonarx@gmail.com>"]
edition = "2018"

[dependencies]
# Only needed for implementing a UT utility.
rand = "0.7.3"
async-trait = "0.1.24"